name: Build
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pixie-firmware
      uses: actions/checkout@v3
      with:
        ref: chore/add-submodules
        submodules: 'recursive'
    - name: Verify user
      run: echo $UID
    - name: Build pixie-firmware using Docker
      run: |
        docker run --rm -v $PWD:/project -w /project -u $UID -e HOME=/tmp espressif/idf idf.py build
    - name: Verify assets
      run: |
        ls -l ${{ github.workspace }}/pixie-firmware/build/pixie.bin
        ls -l ${{ github.workspace }}/pixie-firmware/build/bootloader/bootloader.bin
        ls -l ${{ github.workspace }}/pixie-firmware/build/partition_table/partition-table.bin
        
  
